services:
  go-app:
    container_name: app
    image: app_image
    build: .
    environment:
      NUMBERS_DBDSL: "host=go_db user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5431:5432"
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
